### ISSUE TITLE
Only show max 12 courses randomly

### ISSUE THREAD

**Issue by aditiapratama** [FaisalUmair/udemy-downloader-gui#5] opened 2017-12-14 05:47 UTC
Hello I have more than 200 courses on Udemy platform, and it seems your apps only show 12 maximum. Is it intentionally or can we search using keyword or list specific course that we want to download?

Thank a lot for awesome apps.

**Comment by FaisalUmair** [comment] 2017-12-14 06:03
Duplicate of #4

**Comment by FaisalUmair** [comment] 2017-12-14 06:07
This has already been fixed in https://github.com/FaisalUmair/udemy-downloader-gui/commit/b92086ce54a70ca45e9fbdeb29eca62ad7e0ebb0 

New release soon, with this fix applied. However, you can follow the Developer instructions to get going for now.

Thanks

**Closed by FaisalUmair** 2017-12-14 06:07 UTC

**Comment by FaisalUmair** [comment] 2017-12-15 08:47
The changes made are now available in the [latest](https://github.com/FaisalUmair/udemy-downloader-gui/releases/latest) release.

Download the new version and it should show all the courses you have enrolled in.

**Comment by aditiapratama** [comment] 2017-12-15 08:52
Thank you so much

Best regards,

Aditia A. Pratama
