### ISSUE TITLE
whin i pressed puse and close app the app repet all downloads from starting

### ISSUE THREAD

**Issue by Mohanneed** [FaisalUmair/udemy-downloader-gui#42] opened 2018-02-21 15:18 UTC

**Comment by FaisalUmair** [comment] 2018-03-02 17:35
Duplicate of #16

**Comment by FaisalUmair** [comment] 2018-03-04 15:25
Please download the latest version from [here](https://github.com/FaisalUmair/udemy-downloader-gui/releases/latest)  and let me know if the problem has been resolved.

Thanks

**Closed** 2018-05-18 07:19 UTC
