### ISSUE TITLE
Login issue is back

### ISSUE THREAD

**Issue by raghavgrover** [FaisalUmair/udemy-downloader-gui#103] opened 2018-05-24 11:53 UTC
Udeler was working fine till noon. I just now tried and faced the Incorrect/Username password error.
Using v1.5.2 on Windows 10

**Comment by spairous** [comment] 2018-05-24 12:38
Confirm having an issue again now and was able to download correcly courses earlier today!
Using v1.5.2 on Windows 10/7

**Comment by zakkimughal** [comment] 2018-05-24 14:54
I confirm it's coming again @FaisalUmair

**Comment by Labkhand1359** [comment] 2018-05-24 15:31
Incorrect username/password error again. version 1.5.2 Mac

**Comment by guibellotti** [comment] 2018-05-24 19:15
Same thing... 'Incorrect username/password'. Windows 10

**Comment by ashik685** [comment] 2018-05-24 19:25
Login issue back

**Comment by RhinojosaDeveloper** [comment] 2018-05-24 19:39
Same thing... 'Incorrect username/password'. Windows 7-64 bits - Using v1.5.2

**Comment by Dimensional** [comment] 2018-05-24 21:29
Udemy seems to be changing things left and right to block downloaders. Is there a chance the user agent string might be the cause of it, that it should be changed?

**Comment by vladdypwnz** [comment] 2018-05-24 22:39
Yikes. Seeing the same thing. Looks like I missed a window of opportunity here

**Comment by ExtivenSulbaran** [comment] 2018-05-25 05:27
BRO dejo de funcionar el udeler no me inicia sesion :S

**Comment by FaisalUmair** [comment] 2018-05-25 07:45
I will fix the issue shortly and publish a new version. I will also add a feature which will remember the user session and use the same every time  a user starts the app. This should take off a lot from the login function and will prevent Udemy servers from getting upset.

**Comment by neo2311** [comment] 2018-05-25 09:50
Hey Faisal share some debugging steps so that we can also contribute to this.

**Comment by FrederickGIT** [comment] 2018-05-25 11:48
Not entirely related, but when is the caption selection update going to come out?

Just because if they keep changing login stuff it will keep getting delayed forever, and I fear that if they squash downloaders altogether I'll never be able to get my captions then, if you keep chasing login updates.

**Comment by FaisalUmair** [comment] 2018-05-25 12:37
@neo2311 The application runs inside a chromium browser. I disable the dev tools for production version. You can clone the application and enable it. What I am looking for currently is where the login request actually fails and why. You can compare the real udemy website  login request in your web browser and the login request in Udeler. 

For now I have managed to fix this, and have also added the feature which will use the previous login session so that the user doesn't have to login again.

@FrederickGIT Logging in is obviously a crucial part of  this application, without that there will be no course downloads/ no subtitles. I will be a pushing a new update which will fix the current login issue and as I mentioned before the feature to resume session will be also added which hopefully will help users maintain session and reduce the number of login requests which will overall make the login much stable and this will also give me some time to work on subtitle language.

I have already planned what I need to add for subtitle language and it won't take long. I think the update to fix subtitle issue should be ready in couple of days if not by tomorrow.

**Comment by Galibri** [comment] 2018-05-25 13:28
The login issues is still there.

**Comment by ashik685** [comment] 2018-05-25 13:31
Waiting for new version bro.

**Comment by FaisalUmair** [comment] 2018-05-25 14:09
Download v1.5.3 and let me know if the problem has been resolved.

**Comment by raghavgrover** [comment] 2018-05-25 14:29
Thanks Faisal. I see an unexpected behavior after closing the app and starting it. It doesn't show any courses and says "No courses found".

![image](https://user-images.githubusercontent.com/10961623/40549730-d899a85e-6055-11e8-9d1a-7fbcd0d574a9.png)

Downloaded courses which completed do not show the message "Download Complete" after restarting the app.

**Comment by raghavgrover** [comment] 2018-05-25 14:33
Tried to resume the partially completed courses from the downloads window and received this error:

![image](https://user-images.githubusercontent.com/10961623/40550033-a3e7a826-6056-11e8-8a4b-410e7268b726.png)

**Comment by FaisalUmair** [comment] 2018-05-25 14:49
@raghavgrover Try logging out and login again.  See if it resolves the problem.

I didn't test the windows version but for me on Mac it is working fine.

**Comment by FaisalUmair** [comment] 2018-05-25 15:21
Yes the reason why it doesn't show the downloaded ones is because the app populates downloads on app exit. Since you already had logged in with bad session it might have not added the downloads in the download tab and upon closing the app it cleared the downloads.

And yes I am aware of the subtitle issue, it uses a different method to download and therefore is a little different in behaviour the actual lecture file downloads. I will try to improve it in next release.

**Comment by M1que4s** [comment] 2018-05-25 15:31
Login error :( 
![image](https://user-images.githubusercontent.com/31262466/40552854-f68dc396-600e-11e8-9f55-e200da00dcdc.png)

**Comment by Galibri** [comment] 2018-05-25 15:35
It's working fine for me now on Windows 10, x64. App version 1.5.3

**Comment by M1que4s** [comment] 2018-05-25 15:51
yes, I already updated the app to version 1.5.3 and the problem was solved :) 👍

**Comment by MaskyS** [comment] 2018-05-25 23:02
Weird, all you did was change the version number (that's what I see through the commit at least) and yet it's working now. Wonder what's causing this issue.

**Comment by FaisalUmair** [comment] 2018-05-26 05:31
@MaskyS You are looking at the latest commit only.
Check https://github.com/FaisalUmair/udemy-downloader-gui/commit/cde648ea714fdfae96a0c40276e132ebe6bff7ec and https://github.com/FaisalUmair/udemy-downloader-gui/commit/aadf80c2da2f4cdfe81995e33c0753af74e6703e

And Udemy is probably blocking certain login which do not contain all cookies as to how the request on a normal web browser should contain and sometimes it just works by making small changes to the request headers or request endpoint. Its weird and I think they might also be blocking requests based on its similarity to the ones they have already blocked and therefore small changes lead to successful login.  They might also counter the latest changes. 

**So my suggestion would be take advantage of the active session and do not logout if you don't need to.**

**Closed** 2018-05-28 18:12 UTC

**Comment by Galibri** [comment] 2018-06-04 16:38
Issue is back again!

**Comment by FaisalUmair** [comment] 2018-06-05 07:21
@Galibri  What version are you using. For me it is working fine on v1.6.0

**Comment by Galibri** [comment] 2018-06-05 07:52
@FaisalUmair Thanks for mentioning the latest release. It's working for me now and it's the latest v1.6.0
