### ISSUE TITLE
1.5.3 User Name and Password Incorrect

### ISSUE THREAD

**Issue by 3DNut** [FaisalUmair/udemy-downloader-gui#105] opened 2018-05-25 20:17 UTC
I tried to login in with 1.5.3 and got the familiar login issue.

**Comment by FaisalUmair** [comment] 2018-05-26 05:34
Hello @3DNut Wait for some time and login again. Do not logout if you don't need to. Keep the session active to minimise the number of login requests.

**Comment by 1Busayo** [comment] 2018-05-26 08:12
i cant login 


![cudeapture](https://user-images.githubusercontent.com/35940016/40574114-e405c5dc-60c4-11e8-83cd-1bf19164615b.PNG)

**Comment by 3DNut** [comment] 2018-05-26 13:40
I waited 24 hours and same thing. I haven't ever had a successful login in the past 3 revisions.

**Comment by jimmy8646** [comment] 2018-05-26 13:45
Same issue here version:1.5.3

**Comment by FaisalUmair** [comment] 2018-05-26 13:48
I am working on a proper/permanent fix for this. I think the login should work fine after that.

**Comment by caneto** [comment] 2018-05-26 14:01
Not Work, not login, verision 1.53...

**Comment by AyaskantaIBM** [comment] 2018-05-26 14:32
I am again facing same login issues. Could you please help with.

**Comment by abuvanth** [comment] 2018-05-26 16:18
same issue

**Comment by Bionic31** [comment] 2018-05-26 16:26
sir looks like the same issue has aroused again 

keep us update when it's fixed, please
Thanks

**Comment by prakass1** [comment] 2018-05-26 16:30
@FaisalUmair looks the issue is still there.

Keep us posted on the fix.

Thanks

**Comment by FaisalUmair** [comment] 2018-05-26 17:03
Yes @prakass1 I am uploading the new version.

**Comment by FaisalUmair** [comment] 2018-05-26 17:28
This issue has been fixed in v1.5.4. Download and provide feedback.

**Comment by suksin** [comment] 2018-05-26 17:53
@FaisalUmair Wondering if this works with Single Sign-on Udemy for Business?

**Comment by lrdeoliveira** [comment] 2018-05-26 19:38
download error, not low. Login but not download

**Comment by Bionic31** [comment] 2018-05-26 22:27
thanks for new feature you add

**Comment by FaisalUmair** [comment] 2018-05-27 04:54
@suksin Good point. I think it would be safe for us to make `www` dynamic and replace it with business subdomain for login also. 

But if anyone here has a business account they can check if the login is working for them. Then we can deal with it accordingly.

**Comment by FaisalUmair** [comment] 2018-05-27 06:50
@Bionic31 No, I am a Student.

**Comment by lucianene** [comment] 2018-05-27 10:47
@FaisalUmair thanks dude, you are awesome!

**Comment by Bionic31** [comment] 2018-05-27 11:35
do you have any course on angular 6 or 5

**Comment by 1Busayo** [comment] 2018-05-27 14:29
Version 1.5.4 is working fine

**Comment by FaisalUmair** [comment] 2018-05-27 14:32
@Bionic31 Do you mean if I can suggest any course on AngularJS?

**Comment by Bionic31** [comment] 2018-05-27 14:57
yea one i can download

**Comment by Bionic31** [comment] 2018-05-28 16:11
any

**Closed** 2018-05-28 18:11 UTC
