### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by himanshuamodwala** [FaisalUmair/udemy-downloader-gui#95] opened 2018-05-19 12:34 UTC
Was working till morning today, now all of sudden it gives Incorrect Username/Password. Tried changing the password several time but every time got the same above error

**Comment by omag0** [comment] 2018-05-19 15:04
Same problem here.

**Comment by mohilles** [comment] 2018-05-19 16:05
+

**Comment by Bionic31** [comment] 2018-05-19 19:06
Same here unable 
Please fix it bro

**Comment by sabsab22** [comment] 2018-05-19 22:06
Same problem here.

**Comment by LauretsDev** [comment] 2018-05-20 00:49
+1

**Comment by mahdisky** [comment] 2018-05-20 00:50
1+

**Comment by drsh0** [comment] 2018-05-20 01:28
+1
Linux appimage

**Comment by avj2352** [comment] 2018-05-20 05:03
+1 Windows 7 (x64) too

**Comment by Tiancheng-Luo** [comment] 2018-05-20 05:30
I think the problem is in udemy api

**Comment by combeysamuel** [comment] 2018-05-20 05:30
+1

**Comment by FaisalUmair** [comment] 2018-05-20 06:16
Thank you all for reporting this. Let me check what is wrong and I will update you shortly.

**Comment by Bionic31** [comment] 2018-05-20 06:55
Thank you sir 
Please can we get the version soon enough, cause I need to complete my downloads before this weekend runs off....  Don't have much time on me

**Comment by Bionic31** [comment] 2018-05-20 06:55
Will be glad if done

**Comment by FaisalUmair** [comment] 2018-05-20 06:58
@Bionic31 Uploading right now.

**Comment by FaisalUmair** [comment] 2018-05-20 07:18
I have published v1.5.1. Let me know if the problem has been resolved.

**Comment by LauretsDev** [comment] 2018-05-20 07:36
Resolved in Win 10. Thank you!

**Comment by rafayet13** [comment] 2018-05-20 08:53
Facing Same Problem Since yesterday on my Windows 10.

**Comment by Bionic31** [comment] 2018-05-20 11:11
Thanks is now working bro 
But you could've add to remember on it not anytime we want to access it we need input our details every time

**Comment by Bionic31** [comment] 2018-05-20 11:36
Sir am getting error at a point of the download

**Comment by FaisalUmair** [comment] 2018-05-20 12:13
What error are you getting? And does this happen for only a particular course?

**Comment by sureshds7** [comment] 2018-05-20 15:08
Thanks Bro It's working

**Comment by ooamazingoo** [comment] 2018-05-21 00:29
Hi,not working windows 8.1 Please fix it :)

**Comment by avj2352** [comment] 2018-05-21 02:01
Thanks team ! Issue is now resolved on my laptop (Windows 7) using the latest version 1.5.1

**Comment by Bionic31** [comment] 2018-05-21 10:13
Have fix it bro 
Thanks for the care

**Closed** 2018-05-25 14:11 UTC

**Comment by User72000** [comment] 2019-03-15 15:02
Login is not working from last 2-3 days, it is saying incorrect username/password but the username and password are working in browser and mobile app.

**Comment by supermazenizo** [comment] 2019-03-16 20:12
I have the same issue on Windows 10.

**Comment by jigarthakkar3012** [comment] 2019-03-29 14:16
> Thank you all for reporting this. Let me check what is wrong and I will update you shortly.
> 
> **UPDATE**
> 
> I have identified the cause of this issue and fixed the same. I will soon push the new version and let you know.
> 
> **For those who want to know what the issue was**, actually Udemy has made a slight change in their authentication process where they now have started to check for the origin of the request found in the `origin request header`. I have the now added the origin header to the login request and hardcoded the same to `https://www.udemy.com`

Please help to resolve this login issue. I am also unable to login the udemy downloader.

**Comment by jigarthakkar3012** [comment] 2019-03-29 14:17
![image](https://user-images.githubusercontent.com/18280388/55238873-88ac3700-525b-11e9-90e2-21270cb22a3f.png)
