### ISSUE TITLE
regarding udeler downloding problem

### ISSUE THREAD

**Issue by tushyachutiya** [FaisalUmair/udemy-downloader-gui#106] opened 2018-05-28 17:39 UTC
it is showing no course availabel every time
![image](https://user-images.githubusercontent.com/39707919/40624713-da708ec2-62cb-11e8-810d-ba3b0bdf34f9.png)
 any way thanks for developing this awesome app

**Comment by FaisalUmair** [comment] 2018-05-28 17:47
Does this happen only when you search for course? Or it doesn't show any course at all after you login?

**Comment by tushyachutiya** [comment] 2018-05-28 17:57
it dosent show any course at all

**Comment by tushyachutiya** [comment] 2018-05-28 18:01
normal account

**Comment by FaisalUmair** [comment] 2018-05-28 18:02
When you login do you click on Udemy business? And have you tried to logout and login again?

**Comment by tushyachutiya** [comment] 2018-05-28 18:05
no,i havent clicked on udemy business and i also tried log in log out
several times but it always shows no course availabel

**Comment by FaisalUmair** [comment] 2018-05-28 18:10
Strange looks like there is something wrong with your account probably. I cannot do anything about this as of now because I wont be able to reproduce this from my account. However if you want, you can allow me temporary access to your account to debug this issue.

**Comment by tushyachutiya** [comment] 2018-05-28 18:13
yeah ,its totally fine shall i give you my udemy account password???

**Comment by tushyachutiya** [comment] 2018-05-28 18:14
udemy account - tusharmarathe28079@gmail.com
pass- kal@el123

**Comment by FaisalUmair** [comment] 2018-05-28 18:14
Yes. You can mail me your Udemy email and Password.

**Comment by tushyachutiya** [comment] 2018-05-28 18:16
thanks sir ,for giving me your precious time for solving my problem

**Comment by tushyachutiya** [comment] 2018-05-28 18:27
oh sorry , i didnt know that , next time i will keep that in mind
thanks

**Comment by FaisalUmair** [comment] 2018-05-28 18:27
Ok. Closing this issue.

**Closed by FaisalUmair** 2018-05-28 18:27 UTC
